// https://www.communitybenefitinsight.org/api/get_hospitals.php?state=ok
export const data = [
  {
    "id": "2427",
    "hospital_org_id": "1905",
    "ein": "731444504",
    "name": "Integris Miami Hospital",
    "name_cr": "Integris Miami Hospital",
    "street_address": "200 2nd Ave Sw",
    "city": "Miami",
    "state": "OK",
    "zip_code": "74354",
    "fips_state_and_county_code": "40115",
    "hospital_bed_count": "117",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370004",
    "county": "Ottawa County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2428",
    "hospital_org_id": "1906",
    "ein": "730570773",
    "name": "Newman Memorial Hospital",
    "name_cr": "Newman Memorial Hospital",
    "street_address": "905 South Main Street",
    "city": "Shattuck",
    "state": "OK",
    "zip_code": "73858",
    "fips_state_and_county_code": "40045",
    "hospital_bed_count": "79",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370007",
    "county": "Ellis County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2429",
    "hospital_org_id": "1907",
    "ein": "272716065",
    "name": "Mercy Hospital El Reno",
    "name_cr": "Mercy Hospital El Reno",
    "street_address": "2115 Park View Drive",
    "city": "El Reno",
    "state": "OK",
    "zip_code": "73036",
    "fips_state_and_county_code": "40017",
    "hospital_bed_count": "54",
    "chrch_affl_f": "Y",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370011",
    "county": "Canadian County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2430",
    "hospital_org_id": "1908",
    "ein": "730579285",
    "name": "Mercy Hospital Okc",
    "name_cr": "Mercy Hospital Okc",
    "street_address": "4300 West Memorial Road",
    "city": "Oklahoma City",
    "state": "OK",
    "zip_code": "73120",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "369",
    "chrch_affl_f": "Y",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370013",
    "county": "Oklahoma County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2431",
    "hospital_org_id": "1909",
    "ein": "237456301",
    "name": "Integris Mayes County Medical Center",
    "name_cr": "Mayes County Medical Center",
    "street_address": "111 North Bailey Street",
    "city": "Pryor",
    "state": "OK",
    "zip_code": "74361",
    "fips_state_and_county_code": "40097",
    "hospital_bed_count": "52",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370015",
    "county": "Mayes County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2432",
    "hospital_org_id": "1905",
    "ein": "731444504",
    "name": "Bass Baptist Health Center",
    "name_cr": "Bass Baptist Health Center",
    "street_address": "600 South Monroe",
    "city": "Enid",
    "state": "OK",
    "zip_code": "73702",
    "fips_state_and_county_code": "40047",
    "hospital_bed_count": "183",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370016",
    "county": "Garfield County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2433",
    "hospital_org_id": "1910",
    "ein": "730606129",
    "name": "Jane Phillips Medical Center",
    "name_cr": "Jane Phillips Medical Center",
    "street_address": "3500 Se Frank Phillips Blvd",
    "city": "Bartlesville",
    "state": "OK",
    "zip_code": "74006",
    "fips_state_and_county_code": "40147",
    "hospital_bed_count": "132",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370018",
    "county": "Washington County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2434",
    "hospital_org_id": "1911",
    "ein": "730579295",
    "name": "Great Plains Regional Medical Center",
    "name_cr": "Great Plains Regional Medical Center",
    "street_address": "West Third And Lincoln",
    "city": "Elk City",
    "state": "OK",
    "zip_code": "73648",
    "fips_state_and_county_code": "40009",
    "hospital_bed_count": "62",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370019",
    "county": "Beckham County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2435",
    "hospital_org_id": "1913",
    "ein": "462288155",
    "name": "Mercy Hospital Ada",
    "name_cr": "Mercy Hospital Ada",
    "street_address": "431 North Monte Vista",
    "city": "Ada",
    "state": "OK",
    "zip_code": "74820",
    "fips_state_and_county_code": "40123",
    "hospital_bed_count": "159",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370020",
    "county": "Pontotoc County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2436",
    "hospital_org_id": "1914",
    "ein": "731008550",
    "name": "Duncan Regional Hospital",
    "name_cr": "Duncan Regional Hospital",
    "street_address": "1407 Whisenant Drive",
    "city": "Duncan",
    "state": "OK",
    "zip_code": "74534",
    "fips_state_and_county_code": "40137",
    "hospital_bed_count": "110",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370023",
    "county": "Stephens County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2437",
    "hospital_org_id": "1915",
    "ein": "814322087",
    "name": "Saint Francis Hospital Muskogee",
    "name_cr": "Saint Francis Hospital Muskogee",
    "street_address": "300 Rockefeller Drive",
    "city": "Muskogee",
    "state": "OK",
    "zip_code": "74401",
    "fips_state_and_county_code": "40101",
    "hospital_bed_count": "325",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370025",
    "county": "Muskogee County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2438",
    "hospital_org_id": "1916",
    "ein": "731034824",
    "name": "Integris Baptist Medical Center",
    "name_cr": "Integris Baptist Medical Center",
    "street_address": "3300 Northwest Expressway",
    "city": "Oklahoma City",
    "state": "OK",
    "zip_code": "73112",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "657",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370028",
    "county": "Oklahoma County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2439",
    "hospital_org_id": "1909",
    "ein": "237456301",
    "name": "Integris Clinton Regional Hospital",
    "name_cr": "Integris Clinton Hospital",
    "street_address": "100 North 30th Street",
    "city": "Clinton",
    "state": "OK",
    "zip_code": "73601",
    "fips_state_and_county_code": "40039",
    "hospital_bed_count": "64",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370029",
    "county": "Custer County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2440",
    "hospital_org_id": "1909",
    "ein": "237456301",
    "name": "Integris Blackwell Regional Hospital",
    "name_cr": "",
    "street_address": "710 South 13th Street",
    "city": "Blackwell",
    "state": "OK",
    "zip_code": "74631",
    "fips_state_and_county_code": "40071",
    "hospital_bed_count": "53",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370030",
    "county": "Kay County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2441",
    "hospital_org_id": "1917",
    "ein": "730657693",
    "name": "St Anthony Hospital",
    "name_cr": "St Anthony Hospital",
    "street_address": "205",
    "city": "Oklahoma City",
    "state": "OK",
    "zip_code": "73101",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "686",
    "chrch_affl_f": "Y",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370037",
    "county": "Oklahoma County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2442",
    "hospital_org_id": "1918",
    "ein": "731500629",
    "name": "Mercy Hospital Ardmore",
    "name_cr": "Mercy Hospital Ardmore",
    "street_address": "1011 14th Ave Nw",
    "city": "Ardmore",
    "state": "OK",
    "zip_code": "73401",
    "fips_state_and_county_code": "40019",
    "hospital_bed_count": "190",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370047",
    "county": "Carter County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2443",
    "hospital_org_id": "1919",
    "ein": "736617937",
    "name": "Mccurtain Memorial Hospital",
    "name_cr": "",
    "street_address": "1301 Lincoln Road",
    "city": "Idabel",
    "state": "OK",
    "zip_code": "74745",
    "fips_state_and_county_code": "40089",
    "hospital_bed_count": "91",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370048",
    "county": "McCurtain County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2444",
    "hospital_org_id": "1920",
    "ein": "731279909",
    "name": "Okmulgee Memorial Hospital",
    "name_cr": "Okmulgee Memorial Hospital",
    "street_address": "1401 Morris Drive",
    "city": "Okmulgee",
    "state": "OK",
    "zip_code": "74447",
    "fips_state_and_county_code": "40111",
    "hospital_bed_count": "66",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370057",
    "county": "Okmulgee County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2445",
    "hospital_org_id": "1921",
    "ein": "731430157",
    "name": "Craig General Hospital",
    "name_cr": "Craig General Hospital",
    "street_address": "735 North Foreman",
    "city": "Vinita",
    "state": "OK",
    "zip_code": "74301",
    "fips_state_and_county_code": "40035",
    "hospital_bed_count": "62",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370065",
    "county": "Craig County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2446",
    "hospital_org_id": "1922",
    "ein": "736087821",
    "name": "Latimer County General Hospital",
    "name_cr": "",
    "street_address": "806 State Highway 2 North",
    "city": "Wilburton",
    "state": "OK",
    "zip_code": "74578",
    "fips_state_and_county_code": "40077",
    "hospital_bed_count": "33",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370072",
    "county": "Latimer County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2447",
    "hospital_org_id": "1923",
    "ein": "730700090",
    "name": "Saint Francis Hospital",
    "name_cr": "Saint Francis Hospital",
    "street_address": "6161 S Yale",
    "city": "Tulsa",
    "state": "OK",
    "zip_code": "74136",
    "fips_state_and_county_code": "40143",
    "hospital_bed_count": "1088",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370091",
    "county": "Tulsa County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2448",
    "hospital_org_id": "1924",
    "ein": "731023826",
    "name": "Sayre Memorial Hospital, Inc",
    "name_cr": "Sayre Memorial Hospital",
    "street_address": "911 Hospital Drive",
    "city": "Sayre",
    "state": "OK",
    "zip_code": "73662",
    "fips_state_and_county_code": "40009",
    "hospital_bed_count": "46",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370103",
    "county": "Beckham County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2449",
    "hospital_org_id": "1917",
    "ein": "730657693",
    "name": "Bone And Joint Hospital",
    "name_cr": "",
    "street_address": "1111 North Dewey Avenue",
    "city": "Oklahoma City",
    "state": "OK",
    "zip_code": "73103",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "102",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370105",
    "county": "Oklahoma County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2450",
    "hospital_org_id": "1925",
    "ein": "731089149",
    "name": "Integris Southwest Medical Center",
    "name_cr": "Integris Southwest Medical Center",
    "street_address": "4401 South Western",
    "city": "Oklahoma City",
    "state": "OK",
    "zip_code": "73109",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "334",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370106",
    "county": "Oklahoma County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2451",
    "hospital_org_id": "1905",
    "ein": "731444504",
    "name": "Integris Grove Hospital",
    "name_cr": "Integris Grove Hospital",
    "street_address": "1001 East 18th Street",
    "city": "Grove",
    "state": "OK",
    "zip_code": "74344",
    "fips_state_and_county_code": "40041",
    "hospital_bed_count": "58",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370113",
    "county": "Delaware County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2452",
    "hospital_org_id": "1926",
    "ein": "730579286",
    "name": "St John Medical Center",
    "name_cr": "St John Medical Center",
    "street_address": "1923 South Utica Avenue",
    "city": "Tulsa",
    "state": "OK",
    "zip_code": "74104",
    "fips_state_and_county_code": "40143",
    "hospital_bed_count": "703",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370114",
    "county": "Tulsa County",
    "hospital_bed_size": ">299 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2453",
    "hospital_org_id": "1928",
    "ein": "455055149",
    "name": "St Anthony Shawnee Hospital",
    "name_cr": "St Anthony Shawnee Hospital",
    "street_address": "1102 West Macarthur",
    "city": "Shawnee",
    "state": "OK",
    "zip_code": "74801",
    "fips_state_and_county_code": "40125",
    "hospital_bed_count": "96",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370149",
    "county": "Pottawatomie County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2454",
    "hospital_org_id": "1929",
    "ein": "730790960",
    "name": "Purcell Municipal Hospital",
    "name_cr": "Purcell Municipal Hospital",
    "street_address": "1500 North Green",
    "city": "Purcell",
    "state": "OK",
    "zip_code": "73080",
    "fips_state_and_county_code": "40087",
    "hospital_bed_count": "39",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370158",
    "county": "McClain County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2455",
    "hospital_org_id": "1930",
    "ein": "730977997",
    "name": "Adair County Health Center",
    "name_cr": "Adair County Health Center",
    "street_address": "100 Highway West",
    "city": "Stilwell",
    "state": "OK",
    "zip_code": "74960",
    "fips_state_and_county_code": "40001",
    "hospital_bed_count": "67",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370178",
    "county": "Adair County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2456",
    "hospital_org_id": "1931",
    "ein": "731192765",
    "name": "Lakeside Womens Hospital",
    "name_cr": "Lakeside Womens Hospital",
    "street_address": "11200 North Portland Avenue",
    "city": "Oklahoma City",
    "state": "OK",
    "zip_code": "73120",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "23",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370199",
    "county": "Oklahoma County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2457",
    "hospital_org_id": "1905",
    "ein": "731444504",
    "name": "Integris Canadian Valley Hospital",
    "name_cr": "Integris Canadian Valley Hospital",
    "street_address": "1201 Health Care Parkway",
    "city": "Yukon",
    "state": "OK",
    "zip_code": "73009",
    "fips_state_and_county_code": "40017",
    "hospital_bed_count": "75",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370211",
    "county": "Canadian County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2458",
    "hospital_org_id": "1932",
    "ein": "010603214",
    "name": "Saint Francis Hospital South",
    "name_cr": "Saint Francis Hospital South",
    "street_address": "10501 East 91st Street South",
    "city": "Tulsa",
    "state": "OK",
    "zip_code": "74133",
    "fips_state_and_county_code": "40143",
    "hospital_bed_count": "96",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370218",
    "county": "Tulsa County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2459",
    "hospital_org_id": "1933",
    "ein": "203700131",
    "name": "St John Owasso",
    "name_cr": "St John Owasso",
    "street_address": "12451 E 100th St North",
    "city": "Owasso",
    "state": "OK",
    "zip_code": "74055",
    "fips_state_and_county_code": "40143",
    "hospital_bed_count": "36",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370227",
    "county": "Tulsa County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2460",
    "hospital_org_id": "1909",
    "ein": "237456301",
    "name": "Integris Seminole Medical Center",
    "name_cr": "",
    "street_address": "2401 Wrangler Boulevard",
    "city": "Seminole",
    "state": "OK",
    "zip_code": "74868",
    "fips_state_and_county_code": "40133",
    "hospital_bed_count": "32",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370229",
    "county": "Seminole County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2461",
    "hospital_org_id": "1934",
    "ein": "383833117",
    "name": "St John Broken Arrow",
    "name_cr": "St John Broken Arrow",
    "street_address": "1000 West Boise Circle",
    "city": "Broken Arrow",
    "state": "OK",
    "zip_code": "74012",
    "fips_state_and_county_code": "40143",
    "hospital_bed_count": "44",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "370235",
    "county": "Tulsa County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2462",
    "hospital_org_id": "1935",
    "ein": "451027361",
    "name": "Integris Health Edmond",
    "name_cr": "Integris Health Edmond",
    "street_address": "4801 Integris Parkway",
    "city": "Edmond",
    "state": "OK",
    "zip_code": "73034",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "40",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370236",
    "county": "Oklahoma County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2463",
    "hospital_org_id": "1936",
    "ein": "813747248",
    "name": "Saint Francis Hospital Vinita",
    "name_cr": "Saint Francis Hospital Vinita",
    "street_address": "735 N Foreman",
    "city": "Vinita",
    "state": "OK",
    "zip_code": "74301",
    "fips_state_and_county_code": "40035",
    "hospital_bed_count": "55",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "370237",
    "county": "Craig County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2464",
    "hospital_org_id": "1937",
    "ein": "455199762",
    "name": "Mercy Hospital Watonga",
    "name_cr": "Mercy Hospital Watonga",
    "street_address": "500 N Clarence Nash",
    "city": "Watonga",
    "state": "OK",
    "zip_code": "73772",
    "fips_state_and_county_code": "40011",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371302",
    "county": "Blaine County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2465",
    "hospital_org_id": "1938",
    "ein": "274433830",
    "name": "Mercy Hospital Tishomingo",
    "name_cr": "Mercy Hospital Tishomingo",
    "street_address": "1000 South Byrd",
    "city": "Tishomingo",
    "state": "OK",
    "zip_code": "73460",
    "fips_state_and_county_code": "40069",
    "hospital_bed_count": "25",
    "chrch_affl_f": "Y",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371304",
    "county": "Johnston County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2466",
    "hospital_org_id": "1939",
    "ein": "731440267",
    "name": "Nowata Health Center",
    "name_cr": "Nowata Health Center",
    "street_address": "237 S Locust",
    "city": "Nowata",
    "state": "OK",
    "zip_code": "74048",
    "fips_state_and_county_code": "40105",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371305",
    "county": "Nowata County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2467",
    "hospital_org_id": "1940",
    "ein": "237169376",
    "name": "Pawhuska Hospital, Inc",
    "name_cr": "Pawhuska Hospital Inc",
    "street_address": "1101 East 15th Street",
    "city": "Pawhuska",
    "state": "OK",
    "zip_code": "74056",
    "fips_state_and_county_code": "40113",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371309",
    "county": "Osage County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2468",
    "hospital_org_id": "1941",
    "ein": "263173902",
    "name": "Mercy Hospital Healdton Inc",
    "name_cr": "Mercy Hospital Healdton Inc",
    "street_address": "3462 Hospital Rd",
    "city": "Healdton",
    "state": "OK",
    "zip_code": "73438",
    "fips_state_and_county_code": "40019",
    "hospital_bed_count": "22",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371310",
    "county": "Carter County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2469",
    "hospital_org_id": "1914",
    "ein": "731008550",
    "name": "Jefferson County Hospital",
    "name_cr": "Jefferson County Hospital",
    "street_address": "Intersection Hwy 70 & 81",
    "city": "Waurika",
    "state": "OK",
    "zip_code": "73573",
    "fips_state_and_county_code": "40067",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371311",
    "county": "Jefferson County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2470",
    "hospital_org_id": "1942",
    "ein": "730662663",
    "name": "St John Sapulpa",
    "name_cr": "St John Sapulpa",
    "street_address": "519 South Division",
    "city": "Sapulpa",
    "state": "OK",
    "zip_code": "74067",
    "fips_state_and_county_code": "40037",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371312",
    "county": "Creek County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2471",
    "hospital_org_id": "1944",
    "ein": "463433074",
    "name": "Mercy Hospital Kingfisher",
    "name_cr": "Mercy Hospital Kingfisher",
    "street_address": "1000 Kingfisher Regional Hospital Dr",
    "city": "Kingfisher",
    "state": "OK",
    "zip_code": "73750",
    "fips_state_and_county_code": "40073",
    "hospital_bed_count": "25",
    "chrch_affl_f": "Y",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371313",
    "county": "Kingfisher County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2472",
    "hospital_org_id": "1945",
    "ein": "260532528",
    "name": "Physicians Hospital At Anadarko",
    "name_cr": "Physicians Hospital At Anadarko",
    "street_address": "1002 East Central Blvd",
    "city": "Anadarko",
    "state": "OK",
    "zip_code": "73005",
    "fips_state_and_county_code": "40015",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "371314",
    "county": "Caddo County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2473",
    "hospital_org_id": "1946",
    "ein": "260532635",
    "name": "Stroud Regional Medical Center",
    "name_cr": "Stroud Regional Medical Center",
    "street_address": "2308 Highway 66 West",
    "city": "Stroud",
    "state": "OK",
    "zip_code": "74079",
    "fips_state_and_county_code": "40081",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371316",
    "county": "Lincoln County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2474",
    "hospital_org_id": "1947",
    "ein": "452998842",
    "name": "Mercy Hospital Logan County",
    "name_cr": "Mercy Hospital Logan County",
    "street_address": "200 S Academy Road",
    "city": "Guthrie",
    "state": "OK",
    "zip_code": "73044",
    "fips_state_and_county_code": "40083",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371317",
    "county": "Logan County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2475",
    "hospital_org_id": "1948",
    "ein": "731235996",
    "name": "Coal County",
    "name_cr": "Coal County",
    "street_address": "6 North Covington",
    "city": "Coalgate",
    "state": "OK",
    "zip_code": "74538",
    "fips_state_and_county_code": "40029",
    "hospital_bed_count": "20",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371319",
    "county": "Coal County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2476",
    "hospital_org_id": "1949",
    "ein": "263778478",
    "name": "Cleveland Area Hospital",
    "name_cr": "Cleveland Area Hospital",
    "street_address": "1401 W Pawnee",
    "city": "Cleveland",
    "state": "OK",
    "zip_code": "74020",
    "fips_state_and_county_code": "40117",
    "hospital_bed_count": "14",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "Y",
    "medicare_provider_number": "371320",
    "county": "Pawnee County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2477",
    "hospital_org_id": "1909",
    "ein": "237456301",
    "name": "Integris Marshall County Medical Center",
    "name_cr": "Marshall County Medical Center",
    "street_address": "One Hospital Drive",
    "city": "Madill",
    "state": "OK",
    "zip_code": "73446",
    "fips_state_and_county_code": "40095",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371326",
    "county": "Marshall County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2478",
    "hospital_org_id": "1950",
    "ein": "731506316",
    "name": "Carnegie Tri-County Municipal Hospital",
    "name_cr": "Carnegie Tri-County Municipal Hospit",
    "street_address": "102 North Broadway",
    "city": "Carnegie",
    "state": "OK",
    "zip_code": "73015",
    "fips_state_and_county_code": "40015",
    "hospital_bed_count": "21",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371334",
    "county": "Caddo County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2479",
    "hospital_org_id": "1906",
    "ein": "730570773",
    "name": "Newman Memorial Hospital",
    "name_cr": "Newman Memorial Hospital",
    "street_address": "905 Main Street",
    "city": "Shattuck",
    "state": "OK",
    "zip_code": "73858",
    "fips_state_and_county_code": "40045",
    "hospital_bed_count": "79",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371336",
    "county": "Ellis County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2480",
    "hospital_org_id": "1919",
    "ein": "736617937",
    "name": "Mccurtain Memorial Hospital",
    "name_cr": "Mccurtain Memorial Hospital",
    "street_address": "1301 East Lincoln Road",
    "city": "Idabel",
    "state": "OK",
    "zip_code": "74745",
    "fips_state_and_county_code": "40089",
    "hospital_bed_count": "25",
    "chrch_affl_f": "N",
    "urban_location_f": "N",
    "children_hospital_f": "N",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "371342",
    "county": "McCurtain County",
    "hospital_bed_size": "<100 beds",
    "updated_dt": "October 7, 2022"
  },
  {
    "id": "2481",
    "hospital_org_id": "1951",
    "ein": "730580264",
    "name": "The Childrens Center, Inc",
    "name_cr": "",
    "street_address": "6800 Northwest 39th Expressway",
    "city": "Bethany",
    "state": "OK",
    "zip_code": "73008",
    "fips_state_and_county_code": "40109",
    "hospital_bed_count": "120",
    "chrch_affl_f": "N",
    "urban_location_f": "Y",
    "children_hospital_f": "Y",
    "memb_counc_teach_hosps_f": "N",
    "medicare_provider_number": "373302",
    "county": "Oklahoma County",
    "hospital_bed_size": "100-299 beds",
    "updated_dt": "October 7, 2022"
  }
];

